### ISSUE TITLE
Allow ignoring all attributes

### ISSUE THREAD

**Issue by ismay** [edvardchen/eslint-plugin-i18next#39]
It would be nice to have an explicit way to ignore all attributes as all attribute warnings have been false positives for me so far. Currently I use: 

```
        'i18next/no-literal-string': [
            'error',
            { markupOnly: true, onlyAttribute: [""] },
        ],
```

But that's a rather confusing way of configuring this in my opinion.

**Comment by edvardchen** [comment]
@ismay we could add another option like `ignoreAllAttributes` but then your config would look like:

```js
        'i18next/no-literal-string': [
            'error',
            { markupOnly: true, ignoreAllAttributes: true },
        ],
```
Still awful 

Like I said in [this issue](https://github.com/edvardchen/eslint-plugin-i18next/issues/17#issuecomment-636488165), I hate to add two options.

So, I proposal to extend the `markupOnly` option:

1. `markupOnly: 1` that just validate the text nodes only, ignore all markups' attributes
2. `markupOnly: 2` that validate the text nodes and all markups' attributes

How do you think?

**Comment by ismay** [comment]
Yeah, tricky. I understand your point. I think that the:

```
markupOnly: 1
markupOnly: 2
```

would be a bit confusing though. I think for me, something in this direction would make sense:

```js
// This will lint both markup and attributes
markup: true,
// could also be written as
markup: [true, { attributes: true }],

// This will lint markup but ignore attributes
markup: [true, { attributes: false }],

// This will lint markup and only the foo and bar attributes
markup: [true, { attributes: ['foo', 'bar'] }],

// Turn on only markup
markup: [true, { onlyMarkup: true }],

// Ignore specific attributes
markup: [true, { ignoreAttributes: ['foo', 'bar'] }],
```

Though that's a breaking change, so you might want to give that some time to see whether it covers all usecases (and I'm not a 100% satisfied with the above). But I think with the current configuration I find it a bit tricky to implement this change in a way that's not confusing.

**Comment by edvardchen** [comment]
You make me review current options. We used to add options constantly for solving issues. We should do better.

For example, `onlyAttribute` and `ignoreAttribute` are a pairing and look structureless and verbose.

So I would like to re-design the interface, like:

```json
{
  // default is textOnly, can be textOnly, markupOnly or global
  "mode": "textOnly",
  "words": { "include": [], "exclude": [] },
  "functions": { "include": [], "exclude": [] },
  "templates": true, // validate string template or not
  "markups": {
    "attribute": { "exclude": [], "include": [] }
  },
  "properties": { "include": [], "exclude": [] },
  "components": { "include": [], "exclude": [] }
}
```

### `exclude` and `include`

The `exclude` and `include` were borrowed from [webpack ecosystem](https://webpack.js.org/configuration/). Instead of applying them to filter files, we use them to filter text.

We can do:

1. match all -- just omit two options
2. ignore all -- `"exclude": [".+"]`
3. match some and ignore some -- `"exclude": ["foo"],"include": ["bar.+"]`, both conditions must be satisfied

### mode

Validate only text nodes in markups:

```yaml
rules:
  i18next/no-literal-string:
    - 1
    - mode: textOnly
      # words:
      #   exclude:
      #   include:
```

Validate text and attributes in markups:

```yaml
rules:
  i18next/no-literal-string:
    - 1
    - mode: markupOnly
      # words:
      #   exclude:
      #   include:
      # markups:
      #   attribute:
      #     exclude:
      #     include:
```

Validate all literal strings in whole project:

```yaml
rules:
  i18next/no-literal-string:
    - 1
    - mode: global
      # all other options
```

@ismay tell me your thought
